# Generated by Django 6.0.5 on 2026-06-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitor",
            name="converted_member",
        ),
        migrations.AddField(
            model_name="visitor",
            name="converted_member_name",
            field=models.CharField(
                blank=True,
                help_text="If converted, enter the member name",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=10,
            ),
        ),
    ]
